var cities = [ "Agartala","Agra","Ahmedabad","Ahmednagar","Aizawl","Ajmer","Akola","Alibag","Aligarh","Allahabad","Alleppey","Almora","Alwar","Ambala",
"Amravati","Amritsar","Amroha","Anand","Anandpur Sahib","Ankleshwar","Arpora","Aryankavu","Aurangabad","Auroville","Ayodhya",
"Badlapur","Balipara","Ballabgarh","Bangalore","Bareilly","Belgaum","Bellary","Bhangar","Bharatpur","Bharuch","Bhavnagar",
"Bhawanipatna","Bhilai","Bhopal","Bhubaneswar","Bhuj-Rudramata","Bicholim","Bijapur","Bijnor","Bikaner","Bodh Gaya",
"Bokaro Steel City","Brahmapur","Bundi","Calicut","Cannanore","Chandannagore","Chandausi","Chandigarh","Chandipur","Changanacherry",
"Chengannur","Chennai","Cherthala","Chhatarpur","Chinsurah","Chitradurga","Chittoor","Cochin","Coimbatore","Cuddalore",
"Cuttack","Darjiling","Dehra","Dun","Delhi","Dewas","Dhanbad","Dharamsala","Dindigul","Dungarpur","Durgapur","Elamanchili",
"Ernakulam","Erode","Faridabad","Gandhinagar","Gangtok","Gauhati","Ghaziabad","Gobindgarh","Gorakhpur","Greater Noida","Guntur",
"Gurgaon","Guruvayur","Gwalior","Haridwar","Hazaribag","Hisar","Hosur","Howrah","Hubli","Hyderabad","Igatpuri","Imphal","Indore",
"Itanagar","Jabalpur","Jaipur","Jaisalmer","Jalandhar","Jamnagar","Jamshedpur","Jodhpur","Kakinada","Kaladi","Kalimpong","Kalpetta",
"Kalyan","Kanchipuram","Kannur","Kanpur","Kanyakumari","Kapadvanj","Karauli","Karnal","Karur","Karwar","Kashmir","Kassar","Kausani",
"Khajuraho","Kharagpur","Kishangarh","Kodaikanal","Kolhapur","Kolkata","Kollam","Komarapalayam","Kootanad","Kota","Kothamangalam",
"Kottakkal","Kottayam","Kovilpatti","Kullu","Kumaon","Kumbakonam","Kumta","Lonavala","Lovedale","Lucknow","Ludhiana","Madurai",
"Mamallapuram (Mahabalipuram)","Manali","Mangalore","Manjeri","Mardol","Margao","Matheran","Mathura","Meerut",
"Moradabad","Morbi","Mumbai","Munnar","Mussoorie","Mysore","Nabha","Nadiad","Nagaur","Nagpur","Nainital","Narendranagar","Nasik",
"Navsari","Nawalgarh","Nellore","Noida","Ooty","Panaji","Panchgani","Panchkula","Panipat","Panvel","Patiala","Patna","Pattambi",
"Perumbavoor","Phagwara","Pilani","Ponda","Porbandar","Pune","Puri","Pushkar","Raipur","Rajapalayam","Rajkot",
"Rajpipla","Ramanathapuram","Ranchi","Ratnagiri","Rishikesh","Roorkee","Saharanpur","Salem","Sangli","Satara","Satna",
"Sawai","Madhopur","Secunderabad","Shillong","Shimla","Sidhi","Sirsa","Sivakasi","Solan","Solapur","Sonepat","Srinagar",
"Sullia","Surat","Surendranagar","Tezpur","Thalassery (Tellicherry)","Thane","Thanjavur","Thekkadi","Thiruvalla",
"Thiruvananthapuram (Trivandrum)","Thrissur","Tiruchirappalli","Tirumala","Tirunelveli","Tirupati","Tiruppur","Tirur","Trichur","Tumkur",
"Tuticorin","Udaipur","Udupi","Ulhasnagar","Vadodara","Valsad","Varanasi","Vellore","Vijayawada","Virudunagar","Visakhapatnam",
"Vrindavan","Warangal","Yamunanagar","Yercaud"
];

var states = [
"Andaman & Nicobar","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Delhi","Goa","Gujarat","Haryana",
"Himachal Pradesh","Jammu & Kashmir","Jharkhand","Karnataka","Kerala","Lakshwadeep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya",
"Mizoram","Nagaland","Orissa","Punjab","Rajasthan","Sikkim","Tamil Nadu","Tripura","Uttar Pradesh","Uttaranchal","West Bengal"
];

var countries = [
"Afghanistan",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Arctic Ocean",
"Aruba",
"Ashmore and Cartier Islands",
"Atlantic Ocean",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Baker Island",
"Bangladesh",
"Barbados",
"Bassas da India",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Bouvet Island",
"Brazil",
"British Virgin Islands",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Clipperton Island",
"Cocos Islands",
"Colombia",
"Comoros",
"Cook Islands",
"Coral Sea Islands",
"Costa Rica",
"Cote d'Ivoire",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Democratic Republic of the Congo",
"Djibouti",
"Dominica",
"Dominican Republic",
"East Timor",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Europa Island",
"Falkland Islands (Islas Malvinas)",
"Faroe Islands",
"Fiji",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"French Southern and Antarctic Lands",
"Gabon",
"Gambia",
"Gaza Strip",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Glorioso Islands",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Heard Island and McDonald Islands",
"Honduras",
"Hong Kong",
"Howland Island",
"Hungary",
"Iceland",
"India",
"Indian Ocean",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Jamaica",
"Jan Mayen",
"Japan",
"Jarvis Island",
"Jersey",
"Johnston Atoll",
"Jordan",
"Juan de Nova Island",
"Kazakhstan",
"Kenya",
"Kingman Reef",
"Kiribati",
"Kerguelen Archipelago",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macau",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Micronesia",
"Midway Islands",
"Moldova",
"Monaco",
"Mongolia",
"Montenegro",
"Montserrat",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Navassa Island",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norfolk Island",
"North Korea",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pacific Ocean",
"Pakistan",
"Palau",
"Palmyra Atoll",
"Panama",
"Papua New Guinea",
"Paracel Islands",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn Islands",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Republic of the Congo",
"Romania",
"Russia",
"Rwanda",
"Saint Helena",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Pierre and Miquelon",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Georgia and the South Sandwich Islands",
"South Korea",
"Spain",
"Spratly Islands",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Togo",
"Tokelau",
"Tonga",
"Trinidad and Tobago",
"Tromelin Island",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks and Caicos Islands",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"USA",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Viet Nam",
"Virgin Islands",
"Wake Island",
"Wallis and Futuna",
"West Bank",
"Western Sahara",
"Yemen",
"Yugoslavia",
"Zambia",
"Zimbabwe"
];
